### ISSUE TITLE
using on lora

### ISSUE THREAD

**Issue by halukmy** [J-Rios/Arduino-RFScomm#1]
can we use this algorythm at lora?

**Comment by J-Rios** [comment]
Well, this is a library that uses and is built on top of [AVR-Crypto-Lib](https://wiki.das-labor.org/w/AVR-Crypto-Lib/en) and RF [Manchester](https://mchr3k.github.io/arduino-libs-manchester) libraries...

This library is not directly compatible with LoRa, note that LoRa is a completly different RF modulation.

Sure you can use the AVR-CryptoLib algorithms to built another library that uses some Lora communication (or built it using a Lora library, instead the Manchester) and bring some "security" to the communication, however, I think that this may not be the best approach, because if you use some LoRaWAN layer on top of the LoRa technology (LoRa is just the physical layer), you already has an appropiate encrypted technology and secure communication.

**Comment by halukmy** [comment]
@J-Rios thanks for beautiful message im so happy to see it

i am using https://github.com/sandeepmistry/arduino-LoRa this repo and i just made my own Lora gateway with nodes, write a service application and message on mqtt  to others...

most epic problem is security..

for example i control devices on message

if someone sniff lora message and send it back, other nodes will listen it..

i just find it https://github.com/boseji/xxtea-iot-crypt for secure but i dont think it will secure because, the crypted message will be same mesage as un-crypted..

i will be so happy if you can help on this thanks
